name: VekMiass CI/CD


on:
  push:
    branches:
      - dev
  release:
    types: [published]


jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout
      uses: actions/checkout@master


    - name: Prepare WordPress Zip
      run: |
        WP_LINK=$(cat wp-version-control.cfg)
        wget -O "./wordpress.zip" $WP_LINK
  
    - name: Prepare plugins and theme zip
      run: zip -r wpcontent.zip plugins mu-plugins themes


    - name: Copy Zips to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        source: "./wordpress.zip, ./wpcontent.zip"
        target: ${{ github.event_name == 'push' && 'wordpress_6y9dw/public_html' || 'wordpress_4rgth/public_html' }}


    - name: Enable Maintenance Mode
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        source: ".maintenance"
        target: ${{ github.event_name == 'push' && 'wordpress_6y9dw/public_html' || 'wordpress_4rgth/public_html' }}


    - name: Update WordPress Core
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ${{ github.event_name == 'push' && '~/wordpress_6y9dw/public_html' || '~/wordpress_4rgth/public_html' }}
          find . -maxdepth 1 -type f -name "*.php" ! -name "wp-config.php" -delete
          rm -rf wp-admin wp-includes
          unzip -o wordpress.zip
          mv wordpress/* .
          rmdir wordpress
          rm wordpress.zip


    - name: Update Plugins and Theme
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ${{ github.event_name == 'push' && '~/wordpress_6y9dw/public_html' || '~/wordpress_4rgth/public_html' }}
          rm -rf wp-content/plugins wp-content/mu-plugins wp-content/themes
          unzip -o wpcontent.zip -d wp-content/
          rm wpcontent.zip


    - name: Disable Maintenance Mode and Remove zips
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ${{ github.event_name == 'push' && '~/wordpress_6y9dw/public_html' || '~/wordpress_4rgth/public_html' }}
          rm -f .maintenance wpcontent.zip wordpress.zip
